import { z } from 'zod';

export const BibleCollegeApplicationsSchema = z.object({
  Bible_College_Application_ID: z.number().int(),
  Contact_ID: z.number().int(),
  Participant_ID: z.number().int(),
  Semester: z.number().int().nullable(),
  Occupation: z.string().max(200).nullable(),
  Employer: z.string().max(128).nullable(),
  Employer_Address: z.string().max(255).nullable(),
  Name: z.string().max(128).nullable(),
  Address: z.string().max(255).nullable(),
  Phone: z.string().max(50).nullable(),
  Relationship_ID: z.number().int().nullable(),
  Health: z.boolean().nullable(),
  Last_Medical_Exam: z.string().datetime().nullable(),
  Physical_Handicaps: z.boolean().nullable(),
  Past_Present_Illness: z.string().max(1000).nullable(),
  Communicable_Disease: z.string().max(1000).nullable(),
  Smoker: z.boolean().nullable(),
  Alcohol: z.string().max(2000).nullable(),
  Drugs_Explanation: z.string().max(2000).nullable(),
  Therapy: z.string().max(2000).nullable(),
  Hospitilized: z.string().max(2000).nullable(),
  Abuse_Sexual_Immorality: z.string().max(3000).nullable(),
  Conform_Bible: z.string().max(3000).nullable(),
  Habitual_Sin: z.string().max(3000).nullable(),
  Problem_Relationships: z.string().max(3000).nullable(),
  Cult_Activity: z.string().max(3000).nullable(),
  Salvation: z.string().max(2147483647).nullable(),
  Church_Involvement: z.string().max(3000).nullable(),
  Your_Church: z.string().max(1000).nullable(),
  Attend_Church: z.string().max(255).nullable(),
  How_Long: z.string().max(3000).nullable(),
  Believe_Bible: z.string().max(2000).nullable(),
  Believe_God: z.string().max(2000).nullable(),
  Believe_Jesus: z.string().max(2000).nullable(),
  Believe_Sin: z.string().max(2000).nullable(),
  Believe_Salvation: z.string().max(2000).nullable(),
  Signature: z.string().max(255).nullable(),
  Start_Date: z.string().datetime().nullable(),
  Last_Updated: z.string().datetime().nullable(),
  _Approved: z.boolean().nullable(),
});

export type BibleCollegeApplicationsInput = z.infer<typeof BibleCollegeApplicationsSchema>;
