import { z } from 'zod';

export const CollegeStudentsSchema = z.object({
  Student_ID: z.number().int(),
  Contact_ID: z.number().int(),
  College_Status_ID: z.number().int().nullable(),
  Start_Date: z.string().datetime(),
  End_Date: z.string().datetime().nullable(),
  Notes: z.string().max(2147483647).nullable(),
  Student_Number: z.string().max(11).nullable(),
  Application_Received: z.string().datetime().nullable(),
  Last_Status_Change: z.string().datetime().nullable(),
  Student_Id_Number: z.number().int().nullable(),
  Student_Status_Id: z.number().int().nullable(),
  Last_Name: z.string().max(50).nullable(),
  First_Name: z.string().max(50).nullable(),
  Middle_Name: z.string().max(50).nullable(),
  Name_Suffix: z.string().max(50).nullable(),
  Social_Security_Number: z.string().max(11).nullable(),
  Gender: z.boolean().nullable(),
  Date_of_Birth: z.string().datetime().nullable(),
  Nick_Name: z.string().max(100).nullable(),
  Married: z.boolean().nullable(),
  Student_Living_on_Campus: z.boolean().nullable(),
  Street_address: z.string().max(70).nullable(),
  City: z.string().max(70).nullable(),
  State: z.string().max(50).nullable(),
  Zip: z.string().max(10).nullable(),
  Country: z.string().max(70).nullable(),
  Citizenship: z.string().max(70).nullable(),
  email_address: z.string().max(100).nullable(),
  phone_number: z.string().max(50).nullable(),
  Semester_of_Entry: z.number().nullable(),
  Student_Notes: z.string().max(2147483647).nullable(),
  Billing_Notes: z.string().max(2147483647).nullable(),
  Emergency_Contact: z.string().max(100).nullable(),
  Emergency_Contact_Address: z.string().max(70).nullable(),
  Emergency_Contact_City: z.string().max(70).nullable(),
  Emergency_Contact_State: z.string().max(50).nullable(),
  Emergency_Contact_Zip: z.string().max(10).nullable(),
  Emergency_Contact_Country: z.string().max(70).nullable(),
  Emergency_Contact_Phone: z.string().max(50).nullable(),
  Drivers_license_Number: z.string().max(50).nullable(),
  DL_issuing_state_province: z.string().max(50).nullable(),
  DL_issuing_country: z.string().max(50).nullable(),
  Degree_Conferred: z.string().max(50).nullable(),
  Graduation_Date: z.string().datetime().nullable(),
  Create_date: z.string().datetime().nullable(),
  Update_date: z.string().datetime().nullable(),
  Create_User: z.string().max(50).nullable(),
  Update_User: z.string().max(50).nullable(),
});

export type CollegeStudentsInput = z.infer<typeof CollegeStudentsSchema>;
