import { z } from 'zod';

export const GroupsSchema = z.object({
  Group_ID: z.number().int(),
  Group_Name: z.string().max(75),
  Description: z.string().max(2147483647).nullable(),
  Group_Type_ID: z.number().int(),
  Group_Focus_ID: z.number().int().nullable(),
  Life_Stage_ID: z.number().int().nullable(),
  Ministry_ID: z.number().int(),
  Congregation_ID: z.number().int(),
  Primary_Contact: z.number().int(),
  Start_Date: z.string().datetime(),
  End_Date: z.string().datetime().nullable(),
  Kids_Welcome: z.boolean().nullable(),
  Meeting_Day_ID: z.number().int().nullable(),
  Meeting_Time: z.string().nullable(),
  Meeting_Duration_ID: z.number().int().nullable(),
  Meeting_Frequency_ID: z.number().int().nullable(),
  Group_Meeting_Type_ID: z.number().int().nullable(),
  Required_Book: z.number().int().nullable(),
  Is_Child_Care_Available: z.boolean().nullable(),
  _Last_Attendance_Posted: z.string().datetime().nullable(),
  _Last_Group_Member_Changed: z.string().datetime().nullable(),
  Group_Is_Full: z.boolean(),
  Child_Care_Event: z.number().int().nullable(),
  Max_Child_Care_Count: z.number().int().nullable(),
  Target_Size: z.number().int().nullable(),
  Registration_Start: z.string().datetime().nullable(),
  Registration_End: z.string().datetime().nullable(),
  Available_Online: z.boolean(),
  Meets_Online: z.boolean(),
  Offsite_Meeting_Address: z.number().int().nullable(),
  Default_Room: z.number().int().nullable(),
  Confidential: z.boolean(),
  Parent_Group: z.number().int().nullable(),
  Coach: z.number().int().nullable(),
  Facebook_Group: z.string().max(64).nullable(),
  Reason_Ended: z.number().int().nullable(),
  Descended_From: z.number().int().nullable(),
  Priority_ID: z.number().int().nullable(),
  Create_Outlook_List: z.boolean().nullable(),
  "Secure_Check-in": z.boolean(),
  Suppress_Nametag: z.boolean(),
  Suppress_Care_Note: z.boolean(),
  On_Classroom_Manager: z.boolean(),
  Promote_to_Group: z.number().int().nullable(),
  Age_in_Months_to_Promote: z.number().int().nullable(),
  Promote_Weekly: z.boolean(),
  Promotion_Date: z.string().datetime().nullable(),
  Promote_Participants_Only: z.boolean(),
  Send_Attendance_Notification: z.boolean(),
  Send_Service_Notification: z.boolean(),
  Enable_Discussion: z.boolean(),
  External_System: z.string().max(50).nullable(),
  External_ID: z.string().max(50).nullable(),
  Require_BG_Check: z.boolean(),
  _Approved: z.boolean(),
  Available_On_App: z.boolean().nullable(),
  SMS_Number: z.number().int().nullable(),
  Default_Meeting_Room: z.number().int().nullable(),
  Create_Next_Meeting: z.boolean(),
  Next_Scheduled_Meeting: z.string().datetime().nullable(),
  External_Registration_Url: z.string().max(256).nullable(),
});

export type GroupsInput = z.infer<typeof GroupsSchema>;
