import { z } from 'zod';

export const PocketPlatformSermonsSchema = z.object({
  Sermon_ID: z.number().int(),
  Series_ID: z.number().int(),
  Congregation_ID: z.number().int(),
  Service_Type_ID: z.number().int().nullable(),
  Title: z.string().max(100),
  Subtitle: z.string().max(100).nullable(),
  Description: z.string().max(2147483647).nullable(),
  Sermon_Date: z.string().datetime(),
  Speaker_ID: z.number().int(),
  Scripture_Links: z.string().max(255).nullable(),
  Position: z.number().int().nullable(),
  Use_For_Podcast: z.boolean(),
  Status_ID: z.number().int(),
  Notes_Form_ID: z.number().int().nullable(),
  Sermon_Number: z.string().max(50).nullable(),
  Sermon_Notes: z.string().max(2147483647).nullable(),
  Spanish_Title: z.string().max(200).nullable(),
  Spanish_Notes: z.string().max(2147483647).nullable(),
  Portuguese_Title: z.string().max(200).nullable(),
  Portuguese_Notes: z.string().max(2147483647).nullable(),
  Old_Media_ID: z.number().int().nullable(),
  Locked: z.boolean().nullable(),
  Roku_Episode_Number: z.number().int().nullable(),
  Sermon_UUID: z.string().uuid().nullable(),
  Processing_Complete: z.boolean(),
  Book_ID: z.number().int().nullable(),
  Transcription_Text: z.string().max(2147483647).nullable(),
  Transcription_TimeCode: z.string().max(2147483647).nullable(),
  TranscriptionID: z.string().max(75).nullable(),
  Awaiting_Transcription: z.boolean(),
  Ai_Summary: z.string().max(512).nullable(),
  Ai_Tags: z.string().max(512).nullable(),
  Ai_Word_Count: z.number().int().nullable(),
  Ai_Topics: z.string().max(2147483647).nullable(),
  Ai_Challenge: z.string().max(2000).nullable(),
});

export type PocketPlatformSermonsInput = z.infer<typeof PocketPlatformSermonsSchema>;
