import { z } from 'zod';

export const ProgramsSchema = z.object({
  Program_ID: z.number().int(),
  Program_Name: z.string().max(130),
  Description: z.string().max(255).nullable(),
  Web_Page_URL: z.string().max(150).nullable(),
  FaceBook_URL: z.string().max(150).nullable(),
  Twitter_Username: z.string().max(150).nullable(),
  Google_Circles: z.string().max(150).nullable(),
  Featured_Event: z.number().int().nullable(),
  Congregation_ID: z.number().int(),
  Show_In_Ministries_Directory: z.boolean().nullable(),
  Ministry_ID: z.number().int(),
  Start_Date: z.string().datetime(),
  End_Date: z.string().datetime().nullable(),
  Program_Type_ID: z.number().int().nullable(),
  Leadership_Team: z.number().int().nullable(),
  Ministry_Leader: z.number().int().nullable(),
  Primary_Contact: z.number().int(),
  Volunteer_Contact: z.number().int().nullable(),
  Priority_ID: z.number().int().nullable(),
  Video_Link_Path: z.string().max(150).nullable(),
  Audio_Link_Path: z.string().max(150).nullable(),
  MP_Options: z.string().max(150).nullable(),
  On_Connection_Card: z.boolean(),
  Tax_Deductible_Donations: z.boolean(),
  Statement_Title: z.string().max(50),
  Statement_Header_ID: z.number().int(),
  Allow_Online_Giving: z.boolean(),
  Online_Sort_Order: z.number().int().nullable(),
  Pledge_Campaign_ID: z.number().int().nullable(),
  Default_Target_Event: z.number().int().nullable(),
  On_Donation_Batch_Tool: z.boolean(),
  PMM_Check_Required: z.boolean().nullable(),
  Badge_Title: z.string().max(200).nullable(),
  Disable_Recurring_Gifts: z.boolean().nullable(),
  Available_Online: z.boolean(),
  BG_Check_Ref_Text: z.string().max(50).nullable(),
  Welcome_Message: z.string().max(2147483647).nullable(),
  Custom_App_Question: z.string().max(2000).nullable(),
  Omit_From_Engagement_Giving: z.boolean(),
  OLG_Fund: z.string().max(100).nullable(),
  OLG_Sub_Fund: z.string().max(100).nullable(),
  OLG_Url: z.string().max(255).nullable(),
  Account_Number: z.string().max(25).nullable(),
  Shelby_Fund: z.number().int().nullable(),
  Shelby_Dept: z.number().int().nullable(),
  Shelby_Account: z.number().int().nullable(),
  SMS_Number: z.number().int().nullable(),
  BB_Account_Number: z.string().max(25).nullable(),
  BB_Contra_Income_Account: z.string().max(25).nullable(),
  BB_Liability_Account: z.string().max(25).nullable(),
  BB_Account_Number_Project_ID: z.string().max(25).nullable(),
  BB_Contra_Income_Project_ID: z.string().max(25).nullable(),
  BB_Liability_Account_Project_ID: z.string().max(25).nullable(),
  Vision2_Program_ID: z.string().max(1000).nullable(),
  Vanco_Campaign_ID: z.string().max(255).nullable(),
});

export type ProgramsInput = z.infer<typeof ProgramsSchema>;
