import { z } from 'zod';

export const VolunteerAppsSchema = z.object({
  Volunteer_App_ID: z.number().int(),
  Contact_ID: z.number().int(),
  Start_Date: z.string().datetime(),
  Last_Save_Date: z.string().datetime(),
  Volunteer_App_Status_ID: z.number().int(),
  Status_Reason_ID: z.number().int().nullable(),
  Notes: z.string().max(2147483647).nullable(),
  Follow_Up_Date: z.string().datetime().nullable(),
  Submitted_Date: z.string().datetime().nullable(),
  Clearing_Date: z.string().datetime().nullable(),
  Volunteer_Campus: z.number().int(),
  Occupation: z.string().max(128).nullable(),
  Employee: z.boolean().nullable(),
  Kids: z.string().max(1024).nullable(),
  Other_Church: z.string().max(128).nullable(),
  Statement_Of_Faith: z.boolean().nullable(),
  Disagree_SOF: z.string().max(2048).nullable(),
  Biblical_Lifestyles: z.boolean().nullable(),
  Disagree_BLifestyles: z.string().max(2048).nullable(),
  Salvation_Date: z.string().datetime().nullable(),
  Water_Baptized: z.boolean().nullable(),
  Water_Baptized_Date: z.string().datetime().nullable(),
  Water_Baptized_Location: z.string().max(1024).nullable(),
  Start_Attending_CCM: z.string().datetime().nullable(),
  Attend_How_Often: z.string().max(50).nullable(),
  Testimony: z.string().max(4000).nullable(),
  Gospel: z.string().max(2000).nullable(),
  Devotion_Life: z.string().max(4000).nullable(),
  Talents_Skills_Hobbies: z.string().max(4000).nullable(),
  Classes_Workshops: z.string().max(4000).nullable(),
  Other_Information: z.string().max(4000).nullable(),
  Maiden_Name: z.string().max(100).nullable(),
  Social_Security_Number: z.string().max(50).nullable(),
  Convicted_Crime: z.boolean().nullable(),
  Conviction_Description: z.string().max(4000).nullable(),
  Have_Disease: z.boolean().nullable(),
  Disease_Details: z.string().max(2048).nullable(),
  Digital_Signature: z.string().max(128).nullable(),
  Psychological_Issues: z.boolean().nullable(),
  Psychological_Details: z.string().max(2048).nullable(),
  Abuse_Victim: z.boolean().nullable(),
  Abuse_Details: z.string().max(2048).nullable(),
  Director_Notes: z.string().max(4000).nullable(),
  Last_Contact_Date: z.string().datetime().nullable(),
  OLD_MQID: z.number().int().nullable(),
});

export type VolunteerAppsInput = z.infer<typeof VolunteerAppsSchema>;
